/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.Arrays;
import java.util.stream.IntStream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilantha
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    DefaultTableModel table;
    public MainWindow() {
        initComponents();
        this.setExtendedState(MainWindow.MAXIMIZED_BOTH);
        jtable.setVisible(false);
        buttonSave.setEnabled(false);
        buttonSubmit.setEnabled(false);
        buttonOpen.setEnabled(false);
        buttonNext.setEnabled(false);
        table=(DefaultTableModel)jtable.getModel();
        table.setColumnCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        txtTerm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radioButtonMr = new javax.swing.JRadioButton();
        radioButtonMrs = new javax.swing.JRadioButton();
        radioButtonMs = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        chkboxScience = new javax.swing.JCheckBox();
        chkboxSinhala = new javax.swing.JCheckBox();
        chkboxBuddhism = new javax.swing.JCheckBox();
        chkboxHistory = new javax.swing.JCheckBox();
        chkboxMathematics = new javax.swing.JCheckBox();
        chkboxEnglish = new javax.swing.JCheckBox();
        chkboxElective1 = new javax.swing.JCheckBox();
        chkboxElective2 = new javax.swing.JCheckBox();
        chkboxElective3 = new javax.swing.JCheckBox();
        buttonNext = new javax.swing.JButton();
        chkboxSelectAll = new javax.swing.JCheckBox();
        txtNoStudents = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        buttonExit = new javax.swing.JButton();
        buttonSubmit = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonOpen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Teacher's Name");

        jLabel2.setText("Grade");

        jLabel5.setText("Term");

        radioButtonMr.setText("Mr");

        radioButtonMrs.setText("Mrs");
        radioButtonMrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMrsActionPerformed(evt);
            }
        });

        radioButtonMs.setText("Ms");
        radioButtonMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMsActionPerformed(evt);
            }
        });

        jLabel3.setText("Select the subjects");

        chkboxScience.setText("Science");
        chkboxScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxScienceActionPerformed(evt);
            }
        });

        chkboxSinhala.setText("Sinhala");
        chkboxSinhala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxSinhalaActionPerformed(evt);
            }
        });

        chkboxBuddhism.setText("Buddhism");
        chkboxBuddhism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxBuddhismActionPerformed(evt);
            }
        });

        chkboxHistory.setText("History");
        chkboxHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxHistoryActionPerformed(evt);
            }
        });

        chkboxMathematics.setText("Mathematics");
        chkboxMathematics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxMathematicsActionPerformed(evt);
            }
        });

        chkboxEnglish.setText("English");
        chkboxEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxEnglishActionPerformed(evt);
            }
        });

        chkboxElective1.setText("Elective subject 1");
        chkboxElective1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxElective1ActionPerformed(evt);
            }
        });

        chkboxElective2.setText("Elective subject 2");
        chkboxElective2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxElective2ActionPerformed(evt);
            }
        });

        chkboxElective3.setText("Elective subject 3");
        chkboxElective3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxElective3ActionPerformed(evt);
            }
        });

        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        chkboxSelectAll.setText("Select All");
        chkboxSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxSelectAllActionPerformed(evt);
            }
        });

        jLabel6.setText("No. of students");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNoStudents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(radioButtonMr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButtonMrs)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButtonMs))
                        .addComponent(txtTerm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtGrade, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtTeacherName, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkboxScience)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkboxSinhala)
                            .addComponent(chkboxBuddhism)
                            .addComponent(chkboxHistory)
                            .addComponent(chkboxMathematics)
                            .addComponent(chkboxEnglish)
                            .addComponent(chkboxElective1)
                            .addComponent(chkboxElective2)
                            .addComponent(chkboxElective3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkboxSelectAll)
                    .addComponent(buttonNext))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonMr)
                            .addComponent(radioButtonMrs)
                            .addComponent(radioButtonMs))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkboxScience)
                    .addComponent(chkboxSelectAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxSinhala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxBuddhism)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxMathematics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxEnglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxElective1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxElective2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxElective3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNext)
                .addGap(24, 24, 24))
        );

        jtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonOpen.setText("Open in PDF");

        jButton1.setText("Clear All");

        jButton2.setText("New");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExit)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExit)
                    .addComponent(buttonSubmit)
                    .addComponent(buttonSave)
                    .addComponent(buttonOpen)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        jLabel4.setText("CodeSpark Software Solutions");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Marks Analyzer");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonMrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonMrsActionPerformed

    private void radioButtonMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonMsActionPerformed

    private void chkboxScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxScienceActionPerformed
        if (!chkboxScience.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxScienceActionPerformed

    private void chkboxSinhalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxSinhalaActionPerformed
        if (!chkboxSinhala.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxSinhalaActionPerformed

    private void chkboxMathematicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxMathematicsActionPerformed
        if (!chkboxMathematics.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxMathematicsActionPerformed

    private void chkboxBuddhismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxBuddhismActionPerformed
        if (!chkboxBuddhism.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxBuddhismActionPerformed

    private void chkboxHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxHistoryActionPerformed
        if (!chkboxHistory.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxHistoryActionPerformed

    private void chkboxEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxEnglishActionPerformed
        if (!chkboxEnglish.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxEnglishActionPerformed

    private void chkboxElective1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxElective1ActionPerformed
        if (!chkboxElective1.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_chkboxElective1ActionPerformed

    private void chkboxElective3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxElective3ActionPerformed
        if (!chkboxElective3.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxElective3ActionPerformed

    private void chkboxElective2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxElective2ActionPerformed
        if (!chkboxElective2.isSelected()) {
            chkboxSelectAll.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxElective2ActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void chkboxSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxSelectAllActionPerformed
        if (chkboxSelectAll.isSelected()) {
            chkboxScience.setSelected(true);
            chkboxSinhala.setSelected(true);
            chkboxBuddhism.setSelected(true);
            chkboxHistory.setSelected(true);
            chkboxMathematics.setSelected(true);
            chkboxEnglish.setSelected(true);
            chkboxElective1.setSelected(true);
            chkboxElective2.setSelected(true);
            chkboxElective3.setSelected(true);
        }  else {
            chkboxScience.setSelected(false);
            chkboxSinhala.setSelected(false);
            chkboxBuddhism.setSelected(false);
            chkboxHistory.setSelected(false);
            chkboxMathematics.setSelected(false);
            chkboxEnglish.setSelected(false);
            chkboxElective1.setSelected(false);
            chkboxElective2.setSelected(false);
            chkboxElective3.setSelected(false);
        }
        if (chkboxScience.isSelected() || chkboxSinhala.isSelected() || chkboxEnglish.isSelected() || chkboxHistory.isSelected() || chkboxMathematics.isSelected() || chkboxBuddhism.isSelected() || chkboxHistory.isSelected() || chkboxElective1.isSelected() || chkboxElective2.isSelected() || chkboxElective3.isSelected()) {
            buttonNext.setEnabled(true);
        } else {
            buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxSelectAllActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        buttonNext.setEnabled(false);
        jtable.setVisible(true);
        buttonSubmit.setEnabled(true);
        table.setRowCount(2);
        table.addColumn("Name");
        if (chkboxScience.isSelected()) {
            table.addColumn("Science");
        }
        if (chkboxSinhala.isSelected()) {
            table.addColumn("Sinhala");
        }
        if (chkboxBuddhism.isSelected()) {
            table.addColumn("Buddhism");
        }
        if (chkboxHistory.isSelected()) {
            table.addColumn("History");
        }
        if (chkboxMathematics.isSelected()) {
            table.addColumn("Mathematics");
        }
        if (chkboxEnglish.isSelected()) {
            table.addColumn("English");
        }
        if (chkboxElective1.isSelected()) {
            table.addColumn("Elective1");
        }
        if (chkboxElective2.isSelected()) {
            table.addColumn("Elective2");
        }
        if (chkboxElective3.isSelected()) {
            table.addColumn("Elective3");
        }
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        try {
            jtable.getCellEditor().stopCellEditing();
        } catch (Exception e) {
            System.out.println("");
        }
        
        double tableData[][] = new double[jtable.getRowCount()][jtable.getColumnCount() + 2];
        for (int i = 0; i < jtable.getRowCount(); i++) {
            for (int j = 1; j < jtable.getColumnCount(); j++) {
                System.out.println(table.getValueAt(i, j));
                tableData[i][j] = Integer.parseInt(table.getValueAt(i, j).toString());
            }
        }
        table.addColumn("Total");
        table.addColumn("Average");
        for (int j = 0; j < jtable.getRowCount(); j++) {
            int columnCount = jtable.getColumnCount();
            double temp = 0.0;
            for (int k = 1; k < columnCount - 1; k++) {
                temp = temp + tableData[j][k];
            }
            tableData[j][columnCount - 2] = temp;
            tableData[j][columnCount - 1] = temp / (columnCount - 3);
            table.setValueAt((int)tableData[j][columnCount - 2], j, columnCount - 2);
            table.setValueAt(tableData[j][columnCount - 1], j, columnCount - 1);
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JCheckBox chkboxBuddhism;
    private javax.swing.JCheckBox chkboxElective1;
    private javax.swing.JCheckBox chkboxElective2;
    private javax.swing.JCheckBox chkboxElective3;
    private javax.swing.JCheckBox chkboxEnglish;
    private javax.swing.JCheckBox chkboxHistory;
    private javax.swing.JCheckBox chkboxMathematics;
    private javax.swing.JCheckBox chkboxScience;
    private javax.swing.JCheckBox chkboxSelectAll;
    private javax.swing.JCheckBox chkboxSinhala;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    private javax.swing.JRadioButton radioButtonMr;
    private javax.swing.JRadioButton radioButtonMrs;
    private javax.swing.JRadioButton radioButtonMs;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtNoStudents;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JTextField txtTerm;
    // End of variables declaration//GEN-END:variables
}
